version: "3.8"

services:
  site.homework.local.net:
    ports:
      - "48000:8000"
    command: /start.sh

    user: "${UID-1000}"
    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    volumes:
      - ./storage:/wd/storage:rw

  postgres:
    ports:
      - "53421:5432"
