# Generated by Django 5.0.5 on 2024-05-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField()),
                ('func', models.CharField(max_length=255)),
                ('sequence', models.IntegerField(default=1)),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntegralResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constant', models.CharField()),
                ('function', models.CharField(max_length=255)),
                ('n1', models.FloatField(blank=True, null=True)),
                ('n2', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('is_definite', models.BooleanField(default=False)),
            ],
        ),
    ]
